import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise"],
  env: {
    node: true,
  },
  options: {
    typeAware: true,
  },
  ignorePatterns: ["dist", "node_modules", "coverage", "pnpm-lock.yaml"],
  overrides: [
    {
      files: ["**/*.{test,spec}.ts", "**/test/**/*.ts"],
      rules: {
        "no-empty-function": "off",
        "promise/prefer-await-to-then": "off",
        "promise/prefer-await-to-callbacks": "off",
        "eslint/new-cap": "off",
      },
    },
  ],
  categories: {
    correctness: "error",
    suspicious: "warn",
    perf: "warn",
    style: "warn",
    restriction: "off",
    pedantic: "off",
    nursery: "off",
  },
  rules: {
    eqeqeq: "error",
    "no-var": "error",
    "one-var": "off",
    "prefer-const": "error",
    "no-console": "warn",
    "no-debugger": "error",
    "no-unused-vars": "error",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "object-shorthand": "error",
    "prefer-template": "error",
    "no-param-reassign": "error",
    "no-else-return": "error",
    "init-declarations": "off",
    "id-length": "off",
    "no-magic-numbers": "off",

    "eslint/sort-keys": "off",
    "eslint/func-style": "off",
    "eslint/sort-imports": "off",
    "eslint/max-statements": "off",
    "eslint/no-ternary": "off",

    "import/no-cycle": "error",
    "import/no-self-import": "error",
    "import/no-duplicates": "error",
    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "import/newline-after-import": "error",
    "import/no-named-export": "off",
    "import/group-exports": "off",
    "import/prefer-default-export": "off",

    "promise/prefer-await-to-then": "error",
    "promise/no-nesting": "error",
    "promise/param-names": "error",

    "typescript/no-explicit-any": "warn",
    "typescript/no-unused-vars": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-non-null-assertion": "warn",
    "typescript/array-type": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": "off",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/return-await": ["error", "always"],
    "typescript/only-throw-error": "error",
    "typescript/prefer-return-this-type": "off",
    "typescript/no-unnecessary-type-parameters": "off",

    "unicorn/no-array-for-each": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/no-useless-undefined": "error",
    "unicorn/no-null": "off",
    "unicorn/prefer-module": "error",
    "unicorn/filename-case": "off",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/error-message": "error",
    "unicorn/throw-new-error": "error",
  },
});
